export const SET_MANIFEST_ITEMS = "SET_MANIFEST_ITEMS";

export const SET_VIDEO_NAME = "SET_VIDEO_NAME";
export const SET_VIDEO_PATH = "SET_VIDEO_PATH";
export const SET_VIDEO_PROJECTION = "SET_VIDEO_PROJECTION";
export const SET_VIDEO_SYNOPSIS = "SET_VIDEO_SYNOPSIS";
export const SET_VIDEO_YEAR = "SET_VIDEO_YEAR";
export const SET_VIDEO_POSTER = "SET_VIDEO_POSTER";
export const SET_VIDEO_COUNTRY = "SET_VIDEO_COUNTRY";
export const SET_VIDEO_DURATION = "SET_VIDEO_DURATION";
export const SET_VIDEO_DIRECTOR = "SET_VIDEO_DIRECTOR";
export const SET_VIDEO_ORGANIZATION = "SET_VIDEO_ORGANIZATION";
export const SET_VIDEO_SUBTITLES = "SET_VIDEO_SUBTITLES";
export const SET_VIDEO_GRID_PREVIEW = "SET_VIDEO_GRID_PREVIEW";
export const SET_VIDEO_FRAME_PREVIEW = "SET_VIDEO_FRAME_PREVIEW";

export const SET_CATEGORY_PANORAMA = "SET_CATEGORY_PANORAMA";

export const SET_SETTING_VR_MODE = "SET_SETTING_VR_MODE";
export const SET_SETTING_UI_MODE = "SET_SETTING_UI_MODE";
export const SET_SETTING_PANORAMA = "SET_SETTING_PANORAMA";
export const SET_SETTING_LOGO = "SET_SETTING_LOGO";
export const SET_SETTING_FRAME_COUNT = "SET_SETTING_FRAME_COUNT";

export const LOAD_STORE_FROM_STORAGE = "LOAD_STORE_FROM_STORAGE";
export const SET_CURRENT_PROJECT_DATA_PATH = "SET_CURRENT_PROJECT_DATA_PATH";
export const UPDATE_RECENT_LIST = "UPDATE_RECENT_LIST";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_VIDEO = "ADD_VIDEO";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const SET_ITEM_VISIBLE = "SET_ITEM_VISIBLE";

export const SET_DEVICES = "SET_DEVICES";
export const NEW_PROJECT = 'NEW_PROJECT';
export const OPEN_PROJECT = 'OPEN_PROJECT';
