import { Gems } from "../../ipc/types";

const gems : Gems[] = [
  {"name":"Added Chaos Damage", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/AddedChaosDamage.png?scale=1&w=1&h=1"},
  {"name":"Added Cold Damage", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/AddedColdDamage.png?scale=1&w=1&h=1"},
  {"name":"Added Fire Damage", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/AddedFireDamage.png?scale=1&w=1&h=1"},
  {"name":"Added Lightning Damage", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/AddedLightningDamage.png?scale=1&w=1&h=1"},
  {"name":"Additional Accuracy", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/IncreasedAccuracy.png?scale=1&w=1&h=1"},
  {"name":"Advanced Traps", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/TrapCooldownRecovery.png?scale=1&w=1&h=1"},
  {"name":"Ancestral Call", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/MirageStrike.png?scale=1"},
  {"name":"Ancestral Cry", "iconPath":"https://web.poecdn.com/public/news/2020-06-18/AncestralCry.png"},
  {"name":"Ancestral Protector", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/AncestorTotem.png?scale=1&w=1&h=1"},
  {"name":"Ancestral Warchief", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/SlamTotemGem.png?scale=1&w=1&h=1"},
  {"name":"Anger", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Anger.png?scale=1&w=1&h=1"},
  {"name":"Animate Guardian", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/AnimateArmour.png?scale=1&w=1&h=1"},
  {"name":"Animate Weapon", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/AnimateWeapon.png?scale=1&w=1&h=1"},
  {"name":"Arc", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Arc.png?scale=1&w=1&h=1"},
  {"name":"Arcane Cloak", "iconPath":"https://web.poecdn.com/public/news/2020-03-12/ArcaneCloak.png"},
  {"name":"Arcane Surge", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/ArcaneSurge.png?scale=1"},
  {"name":"Arcanist Brand", "iconPath":"https://web.poecdn.com/public/news/2020-06-18/ArcanistBrand.png"},
  {"name":"Archmage", "iconPath":"https://web.poecdn.com/public/news/2020-03-12/ArchmageSupport.png"},
  {"name":"Arctic Armour", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/IceShield.png?scale=1&w=1&h=1"},
  {"name":"Armageddon Brand", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/ArmageddonBrand.png?scale=1"},
  {"name":"Arrogance", "iconPath":"https://web.poecdn.com/public/news/2021-04-14/ArroganceSupport.png"},
  {"name":"Arrow Nova", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/ArrowNovaSupport.png"},
  {"name":"Artillery Ballista", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/ArtilleryBallista.png"},
  {"name":"Assassin's Mark", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/AssassinsMark.png?scale=1&w=1&h=1"},
  {"name":"Awakened Added Chaos Damage", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedAddedChaosDamageSupport.png"},
  {"name":"Awakened Added Cold Damage", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedAddedColdDamageSupport.png"},
  {"name":"Awakened Added Fire Damage", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedAddedFireDamageSupport.png"},
  {"name":"Awakened Added Lightning Damage", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedAddedLightningDamageSupport.png"},
  {"name":"Awakened Ancestral Call", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedAncestralCallSupport.png"},
  {"name":"Awakened Arrow Nova", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedArrowNovaSupport.png"},
  {"name":"Awakened Blasphemy", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedBlasphemySupport.png"},
  {"name":"Awakened Brutality", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedBrutalitySupport.png"},
  {"name":"Awakened Burning Damage", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedBurningDamageSupport.png"},
  {"name":"Awakened Cast On Critical Strike", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedCastOnCriticalStrikeSupport.png"},
  {"name":"Awakened Cast While Channelling", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedCastWhileChannellingSupport.png"},
  {"name":"Awakened Chain", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedChainSupport.png"},
  {"name":"Awakened Cold Penetration", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedColdPenetrationSupport.png"},
  {"name":"Awakened Controlled Destruction", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedControlledDestructionSupport.png"},
  {"name":"Awakened Deadly Ailments", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedDeadlyAilmentsSupport.png"},
  {"name":"Awakened Elemental Damage With Attacks", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedElementalDamageWithAttacksSupport.png"},
  {"name":"Awakened Elemental Focus", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedElementalFocusSupport.png"},
  {"name":"Awakened Fire Penetration", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedFirePenetrationSupport.png"},
  {"name":"Awakened Fork", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedForkSupport.png"},
  {"name":"Awakened Generosity", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedGenerositySupport.png"},
  {"name":"Awakened Greater Multiple Projectiles", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedGreaterMultipleProjectilesSupport.png"},
  {"name":"Awakened Hextouch", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedCurseOnHitSupport.png"},
  {"name":"Awakened Increased Area Of Effect", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedIncreasedAreaOfEffectSupport.png"},
  {"name":"Awakened Lightning Penetration", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedLightningPenetrationSupport.png"},
  {"name":"Awakened Melee Physical Damage", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedMeleePhysicalDamageSupport.png"},
  {"name":"Awakened Melee Splash", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedMeleeSplashSupport.png"},
  {"name":"Awakened Minion Damage", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedMinionDamageSupport.png"},
  {"name":"Awakened Multistrike", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedMultistrikeSupport.png"},
  {"name":"Awakened Spell Cascade", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedSpellCascadeSupport.png"},
  {"name":"Awakened Spell Echo", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedSpellEchoSupport.png"},
  {"name":"Awakened Swift Affliction", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedSwiftAfflictionSupport.png"},
  {"name":"Awakened Unbound Ailments", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedUnboundAilmentsSupport.png"},
  {"name":"Awakened Unleash", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedUnleashSupport.png"},
  {"name":"Awakened Vicious Projectiles", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedViciousProjectilesSupport.png"},
  {"name":"Awakened Void Manipulation", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/AwakenedVoidManipulationSupport.png"},
  {"name":"Ball Lightning", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/BallLightning.png?scale=1&w=1&h=1"},
  {"name":"Ballista Totem", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/RangedAttackTotem.png?scale=1&w=1&h=1"},
  {"name":"Bane", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/DarkRitualGem.png?scale=1"},
  {"name":"Barrage", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Barrage.png?scale=1"},
  {"name":"Barrage Support", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/BarrageSupport.png"},
  {"name":"Bear Trap", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/BearTrap.png?scale=1&w=1&h=1"},
  {"name":"Berserk", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/Berserk.png"},
  {"name":"Blade Blast", "iconPath":"https://web.poecdn.com/public/news/2020-03-12/BladeBlast.png"},
  {"name":"Blade Flurry", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/ChargedAttack.png?scale=1"},
  {"name":"Blade Vortex", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/SpinningEtherealBladesGem.png?scale=1&w=1&h=1"},
  {"name":"Bladefall", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/RainOfBlades.png?scale=1&w=1&h=1"},
  {"name":"Bladestorm", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/Bladestorm.png"},
  {"name":"Blasphemy", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/Aurify.png?scale=1&w=1&h=1"},
  {"name":"Blast Rain", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/BlastRainGem.png?scale=1&w=1&h=1"},
  {"name":"Blastchain Mine", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/BlastchainMineSupport.png"},
  {"name":"Blazing Salvo", "iconPath":"https://web.poecdn.com/public/news/2020-09-17/SuperiorBlazingSalvo.png"},
  {"name":"Blight", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/BlightGem.png?scale=1"},
  {"name":"Blind", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/Blind.png?scale=1&w=1&h=1"},
  {"name":"Blink Arrow", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/BlinkArrow.png?scale=1&w=1&h=1"},
  {"name":"Block Chance Reduction", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/BreakBlock.png?scale=1&w=1&h=1"},
  {"name":"Blood Rage", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/BloodRage.png?scale=1&w=1&h=1"},
  {"name":"Blood and Sand", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/BloodandSand.png"},
  {"name":"Bloodlust", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/Bloodlust.png?scale=1&w=1&h=1"},
  {"name":"Bloodthirst", "iconPath":"https://web.poecdn.com/public/news/2021-04-14/BloodthirstSupport.png"},
  {"name":"Bodyswap", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/CorpseWarp.png?scale=1"},
  {"name":"Bone Offering", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/BoneOffering.png?scale=1&w=1&h=1"},
  {"name":"Bonechill", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/BoneChillSupport.png?scale=1"},
  {"name":"Brand Recall", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/RecallSigil.png?scale=1"},
  {"name":"Brutality", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/Brutality.png?scale=1"},
  {"name":"Burning Arrow", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/BurningArrow.png?scale=1&w=1&h=1"},
  {"name":"Burning Damage", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/IncreasedBurnDuration.png?scale=1&w=1&h=1"},
  {"name":"Carrion Golem", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/SummonCarrionGolem.png"},
  {"name":"Cast On Critical Strike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/CastOnCrit.png?scale=1&w=1&h=1"},
  {"name":"Cast on Death", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/CastOnDeath.png?scale=1&w=1&h=1"},
  {"name":"Cast on Melee Kill", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/CastOnMeleeKill.png?scale=1&w=1&h=1"},
  {"name":"Cast when Damage Taken", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/CastOnDmgTaken.png?scale=1&w=1&h=1"},
  {"name":"Cast when Stunned", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/CastOnStun.png?scale=1&w=1&h=1"},
  {"name":"Cast while Channelling", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/CastWhileChanneling.png?scale=1"},
  {"name":"Caustic Arrow", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/PoisonArrow.png?scale=1&w=1&h=1"},
  {"name":"Chain", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/chain.png?scale=1&w=1&h=1"},
  {"name":"Chain Hook", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/ChainHook.png"},
  {"name":"Chance to Bleed", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/ChanceToBleed.png?scale=1"},
  {"name":"Chance to Flee", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/ChancetoFlee.png?scale=1&w=1&h=1"},
  {"name":"Charged Dash", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/ChargedDashGem.png?scale=1"},
  {"name":"Charged Mines", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/ChargedMinesSupport.png"},
  {"name":"Charged Traps", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/PowerFrenzyCharge.png?scale=1"},
  {"name":"Clarity", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Clarity.png?scale=1&w=1&h=1"},
  {"name":"Cleave", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Cleave.png?scale=1&w=1&h=1"},
  {"name":"Close Combat", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/CloseCombatSupport.png"},
  {"name":"Cluster Traps", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/ClusterTrap.png?scale=1&w=1&h=1"},
  {"name":"Cobra Lash", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/CobraLash.png"},
  {"name":"Cold Penetration", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/ColdPenetration.png?scale=1&w=1&h=1"},
  {"name":"Cold Snap", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ColdSnap.png?scale=1&w=1&h=1"},
  {"name":"Cold to Fire", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/ColdtoFire.png?scale=1&w=1&h=1"},
  {"name":"Combustion", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/ChancetoIgnite.png?scale=1&w=1&h=1"},
  {"name":"Concentrated Effect", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/ConcentratedAOE.png?scale=1&w=1&h=1"},
  {"name":"Conductivity", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Conductivity.png?scale=1&w=1&h=1"},
  {"name":"Consecrated Path", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/HolyPathGem.png?scale=1"},
  {"name":"Contagion", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ContagionGem.png?scale=1&w=1&h=1"},
  {"name":"Controlled Destruction", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/ControlledDestructionGem.png?scale=1&w=1&h=1"},
  {"name":"Conversion Trap", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ConversionTrap.png?scale=1&w=1&h=1"},
  {"name":"Convocation", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Convocation.png?scale=1&w=1&h=1"},
  {"name":"Corrupting Fever", "iconPath":"https://web.poecdn.com/public/news/2021-04-14/CorruptingFever.png"},
  {"name":"Crackling Lance", "iconPath":"https://web.poecdn.com/public/news/2020-09-17/SuperiorCracklingLance.png"},
  {"name":"Creeping Frost", "iconPath":"https://web.poecdn.com/public/news/2020-06-18/CreepingFrost.png"},
  {"name":"Cremation", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/CorpseEruption.png?scale=1"},
  {"name":"Cruelty", "iconPath":"https://web.poecdn.com/public/news/2021-04-14/CrueltySupport.png"},
  {"name":"Culling Strike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/CullingStrike.png?scale=1&w=1&h=1"},
  {"name":"Cyclone", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Cyclone.png?scale=1&w=1&h=1"},
  {"name":"Damage on Full Life", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/MeleeDamageonFullLife.png?scale=1&w=1&h=1"},
  {"name":"Dark Pact", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/SkeletalChains.png?scale=1"},
  {"name":"Dash", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/Dash.png"},
  {"name":"Deadly Ailments", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/DeadlyAilments.png?scale=1"},
  {"name":"Decay", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/Decay.png?scale=1"},
  {"name":"Decoy Totem", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/DecoyTotem.png?scale=1&w=1&h=1"},
  {"name":"Desecrate", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Desecrate.png?scale=1&w=1&h=1"},
  {"name":"Despair", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Despair.png?scale=1"},
  {"name":"Determination", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Determination.png?scale=1&w=1&h=1"},
  {"name":"Detonate Dead", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/DetonateDead.png?scale=1&w=1&h=1"},
  {"name":"Detonate Mines", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/DetonateMines.png?scale=1&w=1&h=1"},
  {"name":"Devouring Totem", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/DevouringTotem.png?scale=1&w=1&h=1"},
  {"name":"Discharge", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Discharge.png?scale=1&w=1&h=1"},
  {"name":"Discipline", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Discipline.png?scale=1&w=1&h=1"},
  {"name":"Divine Ire", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/DivineTempest.png?scale=1"},
  {"name":"Dominating Blow", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/DominatingBlow.png?scale=1&w=1&h=1"},
  {"name":"Double Strike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/DoubleStrike.png?scale=1&w=1&h=1"},
  {"name":"Dread Banner", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/DreadBanner.png?scale=1"},
  {"name":"Dual Strike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/DualStrike.png?scale=1&w=1&h=1"},
  {"name":"Earthquake", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/QuakeSlam.png?scale=1&w=1&h=1"},
  {"name":"Earthshatter", "iconPath":"https://web.poecdn.com/public/news/2020-06-18/Earthshatter.png"},
  {"name":"Efficacy", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/Efficacy.png?scale=1"},
  {"name":"Elemental Army", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/ElementalArmySupport.png"},
  {"name":"Elemental Damage with Attacks", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/WeaponElementalDamage.png?scale=1&w=1&h=1"},
  {"name":"Elemental Focus", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/ElementalFocus.png?scale=1&w=1&h=1"},
  {"name":"Elemental Hit", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Elementalhit.png?scale=1&w=1&h=1"},
  {"name":"Elemental Penetration", "iconPath":"https://web.poecdn.com/public/news/2020-09-17/SuperiorElementalPenetrationSupport.png"},
  {"name":"Elemental Proliferation", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/ElementalProliferation.png?scale=1&w=1&h=1"},
  {"name":"Elemental Weakness", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ElementalWeakness.png?scale=1&w=1&h=1"},
  {"name":"Empower", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/Empower.png?scale=1&w=1&h=1"},
  {"name":"Endurance Charge on Melee Stun", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/EnduranceChargeStun.png?scale=1&w=1&h=1"},
  {"name":"Enduring Cry", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/EnduringCry.png?scale=1&w=1&h=1"},
  {"name":"Energy Leech", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/EnergyShieldLeechsupport.png?scale=1"},
  {"name":"Enfeeble", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Enfeeble.png?scale=1&w=1&h=1"},
  {"name":"Enhance", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/enhance.png?scale=1&w=1&h=1"},
  {"name":"Enlighten", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/Enlighten.png?scale=1&w=1&h=1"},
  {"name":"Ensnaring Arrow", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/EnsnaringArrow.png"},
  {"name":"Essence Drain", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/SiphonGem.png?scale=1&w=1&h=1"},
  {"name":"Ethereal Knives", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/EtherealKnives.png?scale=1&w=1&h=1"},
  {"name":"Explosive Arrow", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ExplosiveArrow.png?scale=1&w=1&h=1"},
  {"name":"Explosive Trap", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/ShrapnelTrap.png?scale=1"},
  {"name":"Exsanguinate", "iconPath":"https://web.poecdn.com/public/news/2021-04-14/Exsanguinate.png"},
  {"name":"Faster Attacks", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/FasterAttacks.png?scale=1&w=1&h=1"},
  {"name":"Faster Casting", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/FasterCast.png?scale=1&w=1&h=1"},
  {"name":"Faster Projectiles", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/FasterProjectiles.png?scale=1&w=1&h=1"},
  {"name":"Feeding Frenzy", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/FeedingFrenzySupport.png"},
  {"name":"Fire Penetration", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/FirePenetration.png?scale=1&w=1&h=1"},
  {"name":"Fire Trap", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/FireTrap.png?scale=1&w=1&h=1"},
  {"name":"Fireball", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Fireball.png?scale=1&w=1&h=1"},
  {"name":"Firestorm", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Firestorm.png?scale=1&w=1&h=1"},
  {"name":"Fist of War", "iconPath":"https://web.poecdn.com/public/news/2020-06-18/FistofWarSupport.png"},
  {"name":"Flame Dash", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/FlameDash.png?scale=1&w=1&h=1"},
  {"name":"Flame Surge", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Flamewhip.png?scale=1&w=1&h=1"},
  {"name":"Flame Wall", "iconPath":"https://web.poecdn.com/public/news/2020-09-17/SuperiorFlameWall.png"},
  {"name":"Flameblast", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ChargedBlast.png?scale=1&w=1&h=1"},
  {"name":"Flamethrower Trap", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/FlamethrowerTrap.png?scale=1"},
  {"name":"Flammability", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Flammability.png?scale=1&w=1&h=1"},
  {"name":"Flesh Offering", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/FleshOffering.png?scale=1&w=1&h=1"},
  {"name":"Flesh and Stone", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/FleshandStone.png"},
  {"name":"Flicker Strike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/FlickerStrike.png?scale=1&w=1&h=1"},
  {"name":"Fork", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/Fork.png?scale=1&w=1&h=1"},
  {"name":"Fortify", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/FortifyGem.png?scale=1&w=1&h=1"},
  {"name":"Freezing Pulse", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/FreezingPulse.png?scale=1&w=1&h=1"},
  {"name":"Frenzy", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Frenzy.png?scale=1&w=1&h=1"},
  {"name":"Frost Blades", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/IceStrike.png?scale=1&w=1&h=1"},
  {"name":"Frost Bomb", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/FrostBomb.png?scale=1&w=1&h=1"},
  {"name":"Frost Shield", "iconPath":"https://web.poecdn.com/public/news/2020-09-17/SuperiorFrostShield.png"},
  {"name":"Frost Wall", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/FrostWall.png?scale=1&w=1&h=1"},
  {"name":"Frostbite", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/FrostBite.png?scale=1&w=1&h=1"},
  {"name":"Frostblink", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/Frostblink.png"},
  {"name":"Frostbolt", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/FrostBolt.png?scale=1&w=1&h=1"},
  {"name":"Galvanic Arrow", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ShrapnelShot.png?scale=1&w=1&h=1"},
  {"name":"General's Cry", "iconPath":"https://web.poecdn.com/public/news/2020-06-18/GeneralsCry.png"},
  {"name":"Generosity", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/GenerositySupport.png?scale=1&w=1&h=1"},
  {"name":"Glacial Cascade", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Upheaval.png?scale=1&w=1&h=1"},
  {"name":"Glacial Hammer", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/GlacialHammer.png?scale=1&w=1&h=1"},
  {"name":"Grace", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Grace.png?scale=1&w=1&h=1"},
  {"name":"Greater Multiple Projectiles", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/GreaterMultipleProjectiles.png?scale=1&w=1&h=1"},
  {"name":"Greater Volley", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/GreaterVolleySupport.png"},
  {"name":"Ground Slam", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Groundslam.png?scale=1&w=1&h=1"},
  {"name":"Haste", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Haste.png?scale=1&w=1&h=1"},
  {"name":"Hatred", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Hatred.png?scale=1&w=1&h=1"},
  {"name":"Heavy Strike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/HeavyStrike.png?scale=1&w=1&h=1"},
  {"name":"Herald of Agony", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/HeraldOfAgonyGem.png?scale=1"},
  {"name":"Herald of Ash", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/HeraldofAsh.png?scale=1&w=1&h=1"},
  {"name":"Herald of Ice", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/HeraldofIce.png?scale=1&w=1&h=1"},
  {"name":"Herald of Purity", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/HeraldOfLight%20Gem.png?scale=1"},
  {"name":"Herald of Thunder", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/HeraldofThunder.png?scale=1&w=1&h=1"},
  {"name":"Hexblast", "iconPath":"https://web.poecdn.com/public/news/2020-09-17/SuperiorHexblast.png"},
  {"name":"Hextouch", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/CurseOnHit.png?scale=1&w=1&h=1"},
  {"name":"High-Impact Mine", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/HighImpactMineSupport.png"},
  {"name":"Holy Flame Totem", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/FlameTotem.png?scale=1"},
  {"name":"Hydrosphere", "iconPath":"https://web.poecdn.com/protected/image/echoes/items/Hydrosphere.png?key=I_7oZFEYQ3Dudya6rRg28w"},
  {"name":"Hypothermia", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/DamageAgainstChilled.png?scale=1&w=1&h=1"},
  {"name":"Ice Bite", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/FrenzyChargeOnShatter.png?scale=1&w=1&h=1"},
  {"name":"Ice Crash", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/IceCrashGem.png?scale=1&w=1&h=1"},
  {"name":"Ice Nova", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/IceNova.png?scale=1&w=1&h=1"},
  {"name":"Ice Shot", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/IceShot.png?scale=1&w=1&h=1"},
  {"name":"Ice Spear", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/IceSpear.png?scale=1&w=1&h=1"},
  {"name":"Ice Trap", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/IceTrapRune.png?scale=1&w=1&h=1"},
  {"name":"Icicle Mine", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/IcicleMine.png"},
  {"name":"Ignite Proliferation", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/IgniteProliferation.png?scale=1"},
  {"name":"Immolate", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/Immolate.png?scale=1"},
  {"name":"Immortal Call", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ImmortalCall.png?scale=1&w=1&h=1"},
  {"name":"Impale", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/ImpaleSupport.png"},
  {"name":"Impending Doom", "iconPath":"https://web.poecdn.com/public/news/2020-09-17/SuperiorImpendingDoomSupport.png"},
  {"name":"Incinerate", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Flamethrower.png?scale=1&w=1&h=1"},
  {"name":"Increased Area of Effect", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/IncreasedAOE.png?scale=1&w=1&h=1"},
  {"name":"Increased Critical Damage", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/IncreasedCriticalDamage.png?scale=1&w=1&h=1"},
  {"name":"Increased Critical Strikes", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/IncreasedCriticalStrikes.png?scale=1&w=1&h=1"},
  {"name":"Increased Duration", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/IncreasedDuration.png?scale=1&w=1&h=1"},
  {"name":"Infernal Blow", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/InfernalBlow.png?scale=1&w=1&h=1"},
  {"name":"Infernal Cry", "iconPath":"https://web.poecdn.com/public/news/2020-06-18/InfernalCry.png"},
  {"name":"Infernal Legion", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/InfernalLegionSupport.png"},
  {"name":"Infused Channelling", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/StormBarrier.png?scale=1"},
  {"name":"Innervate", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/OnslaughtOnSlayingShocked.png?scale=1&w=1&h=1"},
  {"name":"Inspiration", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/InspirationSupport.png"},
  {"name":"Intensify", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/SpellFocusSupport.png?scale=1"},
  {"name":"Intimidating Cry", "iconPath":"https://web.poecdn.com/public/news/2020-06-18/IntimidatingCry.png"},
  {"name":"Iron Grip", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/IronGrip.png?scale=1&w=1&h=1"},
  {"name":"Iron Will", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/IronWill.png?scale=1&w=1&h=1"},
  {"name":"Item Rarity", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/IncreasedQuality.png?scale=1&w=1&h=1"},
  {"name":"Kinetic Blast", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ClusterBurst.png?scale=1&w=1&h=1"},
  {"name":"Kinetic Bolt", "iconPath":"https://web.poecdn.com/public/news/2020-03-12/KineticBolt.png"},
  {"name":"Knockback", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/Knockback.png?scale=1&w=1&h=1"},
  {"name":"Lacerate", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/DoubleSlash.png?scale=1&w=1&h=1"},
  {"name":"Lancing Steel", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/LancingSteel.png?scale=1"},
  {"name":"Leap Slam", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/LeapSlam.png?scale=1&w=1&h=1"},
  {"name":"Less Duration", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/ReduceDuration.png?scale=1&w=1&h=1"},
  {"name":"Lesser Multiple Projectiles", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/LesserMultipleProjectiles.png?scale=1&w=1&h=1"},
  {"name":"Lesser Poison", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/LesserPoison.png?scale=1"},
  {"name":"Life Gain on Hit", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/LifeonHit.png?scale=1&w=1&h=1"},
  {"name":"Life Leech", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/LifeLeech.png?scale=1&w=1&h=1"},
  {"name":"Lifetap", "iconPath":"https://web.poecdn.com/public/news/2021-04-14/LifetapSupport.png"},
  {"name":"Lightning Arrow", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/LightningArrow.png?scale=1&w=1&h=1"},
  {"name":"Lightning Penetration", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/LightningPenetration.png?scale=1&w=1&h=1"},
  {"name":"Lightning Spire Trap", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/LightningSpire.png?scale=1"},
  {"name":"Lightning Strike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/LightningStrike.png?scale=1&w=1&h=1"},
  {"name":"Lightning Tendrils", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/LighteningTouch.png?scale=1&w=1&h=1"},
  {"name":"Lightning Trap", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/LightningTrap.png?scale=1&w=1&h=1"},
  {"name":"Lightning Warp", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/LightningWarp.png?scale=1&w=1&h=1"},
  {"name":"Maim", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/Maim.png?scale=1"},
  {"name":"Malevolence", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/SpellFocusSupport.png?scale=1"},
  {"name":"Mana Leech", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/ManaLeech.png?scale=1&w=1&h=1"},
  {"name":"Meat Shield", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/MeatShieldSupport.png"},
  {"name":"Melee Physical Damage", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/IncreasedPhysicalDamage.png?scale=1&w=1&h=1"},
  {"name":"Melee Splash", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/Splash.png?scale=1&w=1&h=1"},
  {"name":"Minefield", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/MinefieldSupport.png"},
  {"name":"Minion Damage", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/MinionDamage.png?scale=1&w=1&h=1"},
  {"name":"Minion Life", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/MinionLife.png?scale=1&w=1&h=1"},
  {"name":"Minion Speed", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/MinionSpeed.png?scale=1&w=1&h=1"},
  {"name":"Mirage Archer", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/MirageArcher.png?scale=1"},
  {"name":"Mirror Arrow", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/MirrorArrow.png?scale=1&w=1&h=1"},
  {"name":"Molten Shell", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/MoltenShell.png?scale=1&w=1&h=1"},
  {"name":"Molten Strike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/MoltenStrike.png?scale=1&w=1&h=1"},
  {"name":"Multiple Totems", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/MultipleTotems.png?scale=1"},
  {"name":"Multiple Traps", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/MultiTrap.png?scale=1&w=1&h=1"},
  {"name":"Multistrike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/multipleattacks.png?scale=1&w=1&h=1"},
  {"name":"Nightblade", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/NightbladeSupport.png"},
  {"name":"Onslaught", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/Onslaught.png?scale=1"},
  {"name":"Orb of Storms", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/StormCloudGem.png?scale=1&w=1&h=1"},
  {"name":"Penance Brand", "iconPath":"https://web.poecdn.com/public/news/2020-06-18/PenanceBrand.png"},
  {"name":"Perforate", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/Perforate.png"},
  {"name":"Pestilent Strike", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/PestilentStrike.png"},
  {"name":"Petrified Blood", "iconPath":"https://web.poecdn.com/public/news/2021-04-14/PetrifiedBlood.png"},
  {"name":"Phase Run", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/PhaseRun.png?scale=1&w=1&h=1"},
  {"name":"Physical to Lightning", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/PhysicalToLightning.png?scale=1&w=1&h=1"},
  {"name":"Pierce", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/Pierce.png?scale=1&w=1&h=1"},
  {"name":"Pinpoint", "iconPath":"https://web.poecdn.com/public/news/2020-09-17/SuperiorPinpointSupport.png"},
  {"name":"Plague Bearer", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/PlagueBearer.png"},
  {"name":"Poacher's Mark", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/PoachersMark.png?scale=1&w=1&h=1"},
  {"name":"Point Blank", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/PointBlank.png?scale=1&w=1&h=1"},
  {"name":"Poison", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/Poison.png?scale=1&w=1&h=1"},
  {"name":"Portal", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Portal.png?scale=1&w=1&h=1"},
  {"name":"Power Charge On Critical", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/PowerCharges.png?scale=1&w=1&h=1"},
  {"name":"Power Siphon", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/PowerSiphon.png?scale=1&w=1&h=1"},
  {"name":"Precision", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/Precision.png"},
  {"name":"Predator", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/DeathmarkSupport.png"},
  {"name":"Pride", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/Pride.png"},
  {"name":"Pulverise", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/PulveriseSupport.png"},
  {"name":"Puncture", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Puncture.png?scale=1&w=1&h=1"},
  {"name":"Punishment", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Punishment.png?scale=1&w=1&h=1"},
  {"name":"Purifying Flame", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/PurifyingFlame.png?scale=1"},
  {"name":"Purity of Elements", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Purity.png?scale=1&w=1&h=1"},
  {"name":"Purity of Fire", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/FireResistAura.png?scale=1&w=1&h=1"},
  {"name":"Purity of Ice", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ColdResistAura.png?scale=1&w=1&h=1"},
  {"name":"Purity of Lightning", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/LightningResistAura.png?scale=1&w=1&h=1"},
  {"name":"Pyroclast Mine", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/PyroclastMine.png"},
  {"name":"Rage", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/RageSupport.png"},
  {"name":"Rain of Arrows", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/RainofArrows.png?scale=1&w=1&h=1"},
  {"name":"Raise Spectre", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/RaiseSpectre.png?scale=1&w=1&h=1"},
  {"name":"Raise Zombie", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/RaiseZombie.png?scale=1&w=1&h=1"},
  {"name":"Rallying Cry", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/InspiringCry.png?scale=1&w=1&h=1"},
  {"name":"Reap", "iconPath":"https://web.poecdn.com/public/news/2021-04-14/Reap.png"},
  {"name":"Reave", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Reave.png?scale=1&w=1&h=1"},
  {"name":"Reckoning", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Repulse.png?scale=1&w=1&h=1"},
  {"name":"Rejuvenation Totem", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/RejuvinationTotem.png?scale=1&w=1&h=1"},
  {"name":"Righteous Fire", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/RighteousFire.png?scale=1&w=1&h=1"},
  {"name":"Riposte", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Riposte.png?scale=1&w=1&h=1"},
  {"name":"Rolling Magma", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/FireMortar.png?scale=1&w=1&h=1"},
  {"name":"Ruthless", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/Ruthless.png?scale=1"},
  {"name":"Scorching Ray", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/FireBeam.png?scale=1"},
  {"name":"Scourge Arrow", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/VirulentArrow.png?scale=1"},
  {"name":"Searing Bond", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/SearingBond.png?scale=1&w=1&h=1"},
  {"name":"Second Wind", "iconPath":"https://web.poecdn.com/public/news/2020-03-12/SecondWindSupport.png"},
  {"name":"Seismic Cry", "iconPath":"https://web.poecdn.com/public/news/2020-06-18/SeismicCry.png"},
  {"name":"Seismic Trap", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/SubterraneanTrap.png?scale=1"},
  {"name":"Shattering Steel", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/ShatteringSteel.png?scale=1"},
  {"name":"Shield Charge", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ShieldCharge.png?scale=1&w=1&h=1"},
  {"name":"Shock Nova", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ShockNova.png?scale=1&w=1&h=1"},
  {"name":"Shockwave", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/ShockwaveSupport.png"},
  {"name":"Shockwave Totem", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ShockwaveTotem.png?scale=1&w=1&h=1"},
  {"name":"Shrapnel Ballista", "iconPath":"https://web.poecdn.com/public/news/2019-12-12/ShrapnelBallista.png"},
  {"name":"Siege Ballista", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/CrossBowTotemGem.png?scale=1&w=1&h=1"},
  {"name":"Sigil of Power", "iconPath":"https://web.poecdn.com/public/news/2020-09-17/SuperiorSigilofPower.png"},
  {"name":"Siphoning Trap", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/IceSiphon.png?scale=1"},
  {"name":"Slower Projectiles", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/SlowerProjectiles.png?scale=1&w=1&h=1"},
  {"name":"Smite", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/SmiteGem.png?scale=1"},
  {"name":"Smoke Mine", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/SmokeBomb.png?scale=1&w=1&h=1"},
  {"name":"Sniper's Mark", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ProjectileWeakness.png?scale=1&w=1&h=1"},
  {"name":"Soulrend", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Soulrend.png?scale=1"},
  {"name":"Spark", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Spark.png?scale=1&w=1&h=1"},
  {"name":"Spectral Shield Throw", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Thrown%20Shield.png?scale=1"},
  {"name":"Spectral Throw", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/GhostlyThrow.png?scale=1&w=1&h=1"},
  {"name":"Spell Cascade", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/SpellCascade.png?scale=1"},
  {"name":"Spell Echo", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/Echo.png?scale=1&w=1&h=1"},
  {"name":"Spell Totem", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/Totem.png?scale=1&w=1&h=1"},
  {"name":"Spellslinger", "iconPath":"https://web.poecdn.com/public/news/2020-03-12/Spellslinger.png"},
  {"name":"Spirit Offering", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/SpiritOffering.png?scale=1&w=1&h=1"},
  {"name":"Split Arrow", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/SplitArrow.png?scale=1&w=1&h=1"},
  {"name":"Splitting Steel", "iconPath":"https://web.poecdn.com/public/news/2020-09-17/SuperiorSplittingSteel.png"},
  {"name":"Static Strike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/StaticGem.png?scale=1&w=1&h=1"},
  {"name":"Steelskin", "iconPath":"https://web.poecdn.com/public/news/2019-06-06/Steelskin.png"},
  {"name":"Storm Brand", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/ConduitSigil.png?scale=1"},
  {"name":"Storm Burst", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/StormBurst.png?scale=1"},
  {"name":"Storm Call", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Stormcall.png?scale=1&w=1&h=1"},
  {"name":"Stormbind", "iconPath":"https://web.poecdn.com/public/news/2020-03-12/Stormbind.png"},
  {"name":"Stormblast Mine", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/StormblastMine.png"},
  {"name":"Stun", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/Stun.png?scale=1&w=1&h=1"},
  {"name":"Summon Chaos Golem", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ChaosElementalSummon.png?scale=1&w=1&h=1"},
  {"name":"Summon Flame Golem", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/FireElementalSummon.png?scale=1&w=1&h=1"},
  {"name":"Summon Holy Relic", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/HolyRelic.png?scale=1"},
  {"name":"Summon Ice Golem", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/IceElementalSummon.png?scale=1&w=1&h=1"},
  {"name":"Summon Lightning Golem", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/LightningGolem.png?scale=1&w=1&h=1"},
  {"name":"Summon Phantasm", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/SummonPhantasm.png?scale=1"},
  {"name":"Summon Raging Spirit", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/SummonElemental.png?scale=1&w=1&h=1"},
  {"name":"Summon Skeleton", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/SummonSkeletons.png?scale=1&w=1&h=1"},
  {"name":"Summon Skitterbots", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/SummonSkitterbots.png"},
  {"name":"Summon Stone Golem", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/RockGolem.png?scale=1&w=1&h=1"},
  {"name":"Sunder", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ShockwaveSlam.png?scale=1&w=1&h=1"},
  {"name":"Sweep", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Sweep.png?scale=1&w=1&h=1"},
  {"name":"Swift Affliction", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/SupportRapidDecayGem.png?scale=1&w=1&h=1"},
  {"name":"Swift Assembly", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/SwiftAssemblySupport.png"},
  {"name":"Swiftbrand", "iconPath":"https://web.poecdn.com/public/news/2020-06-18/SwiftbrandSupport.png"},
  {"name":"Tectonic Slam", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/TectonicSlam.png?scale=1"},
  {"name":"Tempest Shield", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/TempestShield.png?scale=1&w=1&h=1"},
  {"name":"Temporal Chains", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/TemporalChains.png?scale=1&w=1&h=1"},
  {"name":"Tornado Shot", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/TornadoShot.png?scale=1&w=1&h=1"},
  {"name":"Toxic Rain", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/RainofSporesGem.png?scale=1"},
  {"name":"Trap", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/Trap.png?scale=1&w=1&h=1"},
  {"name":"Trap and Mine Damage", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/TrapAndMineDamage.png?scale=1&w=1&h=1"},
  {"name":"Trinity", "iconPath":"https://web.poecdn.com/protected/image/echoes/items/TrinitySupport.png?key=olxW4UsnblEXVX97PS6_MA"},
  {"name":"Unbound Ailments", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/UnboundAilments.png?scale=1"},
  {"name":"Unearth", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/BoneLance.png?scale=1"},
  {"name":"Unleash", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/UnleashSupport.png?scale=1"},
  {"name":"Urgent Orders", "iconPath":"https://web.poecdn.com/public/news/2020-06-18/UrgentOrdersSupport.png"},
  {"name":"Vaal Ancestral Warchief", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/SlamTotemGemVaal.png?scale=1"},
  {"name":"Vaal Arc", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalArc.png?scale=1&w=1&h=1"},
  {"name":"Vaal Blade Vortex", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/VaalGems/VaalSpinningEtherealBladesGem.png?scale=1"},
  {"name":"Vaal Blight", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/VaalGems/VaalBlightGem.png?scale=1"},
  {"name":"Vaal Breach", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/VaalGems/VaalBreachPortal.png?scale=1"},
  {"name":"Vaal Burning Arrow", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalBurningArrow.png?scale=1&w=1&h=1"},
  {"name":"Vaal Clarity", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalClarity.png?scale=1&w=1&h=1"},
  {"name":"Vaal Cold Snap", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalColdSnap.png?scale=1&w=1&h=1"},
  {"name":"Vaal Cyclone", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalCyclone.png?scale=1&w=1&h=1"},
  {"name":"Vaal Detonate Dead", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalDetonateDead.png?scale=1&w=1&h=1"},
  {"name":"Vaal Discipline", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalDiscipline.png?scale=1&w=1&h=1"},
  {"name":"Vaal Double Strike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalDoubleStrike.png?scale=1&w=1&h=1"},
  {"name":"Vaal Earthquake", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/VaalGems/VaalQuakeSlam.png?scale=1"},
  {"name":"Vaal Fireball", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalFireball.png?scale=1&w=1&h=1"},
  {"name":"Vaal Flameblast", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalChargedBlast.png?scale=1&w=1&h=1"},
  {"name":"Vaal Glacial Hammer", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalGlacialHammer.png?scale=1&w=1&h=1"},
  {"name":"Vaal Grace", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalGrace.png?scale=1&w=1&h=1"},
  {"name":"Vaal Ground Slam", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalGroundslam.png?scale=1&w=1&h=1"},
  {"name":"Vaal Haste", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalHaste.png?scale=1&w=1&h=1"},
  {"name":"Vaal Ice Nova", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalIceNova.png?scale=1&w=1&h=1"},
  {"name":"Vaal Immortal Call", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalImmortalCall.png?scale=1&w=1&h=1"},
  {"name":"Vaal Impurity of Fire", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/VaalGems/VaalFireResistAura.png?scale=1"},
  {"name":"Vaal Impurity of Ice", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/VaalGems/VaalColdResistAura.png?scale=1"},
  {"name":"Vaal Impurity of Lightning", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/VaalGems/VaalLightningResistAura.png?scale=1"},
  {"name":"Vaal Lightning Strike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalLightningStrike.png?scale=1&w=1&h=1"},
  {"name":"Vaal Lightning Trap", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalLightningTrap.png?scale=1&w=1&h=1"},
  {"name":"Vaal Lightning Warp", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalLightningWarp.png?scale=1&w=1&h=1"},
  {"name":"Vaal Molten Shell", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalMoltenShell.png?scale=1&w=1&h=1"},
  {"name":"Vaal Power Siphon", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalPowerSiphon.png?scale=1&w=1&h=1"},
  {"name":"Vaal Rain of Arrows", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalRainofArrows.png?scale=1&w=1&h=1"},
  {"name":"Vaal Reave", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalReave.png?scale=1&w=1&h=1"},
  {"name":"Vaal Righteous Fire", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalRighteousFire.png?scale=1&w=1&h=1"},
  {"name":"Vaal Spark", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalSpark.png?scale=1&w=1&h=1"},
  {"name":"Vaal Spectral Throw", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalGhostlyThrow.png?scale=1&w=1&h=1"},
  {"name":"Vaal Storm Call", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalStormcall.png?scale=1&w=1&h=1"},
  {"name":"Vaal Summon Skeletons", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VaalGems/VaalSummonSkeletons.png?scale=1&w=1&h=1"},
  {"name":"Vengeance", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Vengeance.png?scale=1&w=1&h=1"},
  {"name":"Venom Gyre", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/VenomGyre.png"},
  {"name":"Vicious Projectiles", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/RangedPhysicalAttackDamage.png?scale=1&w=1&h=1"},
  {"name":"Vigilant Strike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/VigilantStrikeGem.png?scale=1&w=1&h=1"},
  {"name":"Vile Toxins", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/VileToxins.png?scale=1"},
  {"name":"Viper Strike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ViperStrike.png?scale=1&w=1&h=1"},
  {"name":"Vitality", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Vitality.png?scale=1&w=1&h=1"},
  {"name":"Void Manipulation", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Support/VoidManipulation.png?scale=1&w=1&h=1"},
  {"name":"Void Sphere", "iconPath":"https://web.poecdn.com/public/news/2020-09-17/SuperiorVoidSphere.png"},
  {"name":"Volatile Dead", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/VolatileDead.png?scale=1"},
  {"name":"Volley", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/ParallelProjectile.png?scale=1"},
  {"name":"Vortex", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/FrostVortex.png?scale=1&w=1&h=1"},
  {"name":"Vulnerability", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Vulnerability.png?scale=1&w=1&h=1"},
  {"name":"War Banner", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Warbanner.png?scale=1"},
  {"name":"Warlord's Mark", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/WarlordsMark.png?scale=1&w=1&h=1"},
  {"name":"Wave of Conviction", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Purge.png?scale=1"},
  {"name":"Whirling Blades", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/WhirlingBlades.png?scale=1&w=1&h=1"},
  {"name":"Wild Strike", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/ElementalStrike.png?scale=1&w=1&h=1"},
  {"name":"Winter Orb", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/FrostFury.png?scale=1"},
  {"name":"Wintertide Brand", "iconPath":"https://web.poecdn.com/public/news/2020-06-18/WintertideBrand.png"},
  {"name":"Wither", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/WitherGem.png?scale=1&w=1&h=1"},
  {"name":"Withering Step", "iconPath":"https://web.poecdn.com/public/news/2019-09-04/WitheringStep.png"},
  {"name":"Withering Touch", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/Support/WitherGemSupport.png?scale=1"},
  {"name":"Wrath", "iconPath":"http://webcdn.pathofexile.com/image/Art/2DItems/Gems/Wrath.png?scale=1&w=1&h=1"},
  {"name":"Zealotry", "iconPath":"https://web.poecdn.com/image/Art/2DItems/Gems/SpellDamageGem.png?scale=1"},
  
  ]

export default gems;